library(data.table)
library(dplyr)
library(lubridate)
consumption <- fread("household_power_consumption.txt",sep=";",header=TRUE,na.strings = "?",stringsAsFactors = FALSE)
consumption$DateTime <- dmy_hms(paste(consumption$Date, consumption$Time))
consumed <- filter(consumption, date(consumption$DateTime) == "2007-02-01" | date(consumption$DateTime) == "2007-02-02")
rm(consumption)
hist(consumed$Global_active_power, col="red",ylab="Frequency",xlab="Global Active Power (kilowatts)", main="Global Active Power")
dev.copy(png, file="plot1.png", width = 480, height=480)
dev.off()
